# Net "uz_clk100_[pn]" from "clk100fo" sy89828
set_property IOSTANDARD  LVDS_25 [get_ports clk100_p]
set_property DIFF_TERM   TRUE    [get_ports clk100_p]
set_property PACKAGE_PIN N20     [get_ports clk100_p]
set_property IOSTANDARD  LVDS_25 [get_ports clk100_n]
set_property DIFF_TERM   TRUE    [get_ports clk100_n]
set_property PACKAGE_PIN P20     [get_ports clk100_n]

# Net "mcuclk_copy_[pn]" from "clkcln" lmk03000
set_property IOSTANDARD  LVDS_25 [get_ports mcuclk_copy_p]
set_property PACKAGE_PIN N18     [get_ports mcuclk_copy_p]
set_property DIFF_TERM   TRUE    [get_ports mcuclk_copy_p]
set_property IOSTANDARD  LVDS_25 [get_ports mcuclk_copy_n]
set_property PACKAGE_PIN P19     [get_ports mcuclk_copy_n]
set_property DIFF_TERM   FALSE   [get_ports mcuclk_copy_n]

# Net "clk100_sel" to "clk100fo" sy89828
set_property IOSTANDARD  LVCMOS25 [get_ports clk100_sel]
# set_property PACKAGE_PIN R19      [get_ports clk100_sel]

# Configuration lines for Artix7 FPGA
set_property IOSTANDARD  LVCMOS25 [get_ports a7_cfg_sclk]
set_property PACKAGE_PIN T11      [get_ports a7_cfg_sclk]
set_property IOSTANDARD  LVCMOS25 [get_ports a7_cfg_d_in]
set_property PACKAGE_PIN T10      [get_ports a7_cfg_d_in]
set_property IOSTANDARD  LVCMOS25 [get_ports a7_cfg_program_b]
set_property PACKAGE_PIN T19      [get_ports a7_cfg_program_b]
set_property IOSTANDARD  LVCMOS25 [get_ports a7_cfg_done]
set_property PACKAGE_PIN T12      [get_ports a7_cfg_done]
set_property IOSTANDARD  LVCMOS25 [get_ports a7_cfg_init_b]
set_property PACKAGE_PIN U12      [get_ports a7_cfg_init_b]

# To configure "clkcln" lmk03000
set_property IOSTANDARD  LVCMOS25 [get_ports clkcln_sclk]
set_property PACKAGE_PIN Y18      [get_ports clkcln_sclk]
set_property IOSTANDARD  LVCMOS25 [get_ports clkcln_sdat]
set_property PACKAGE_PIN V16      [get_ports clkcln_sdat]
set_property IOSTANDARD  LVCMOS25 [get_ports clkcln_sle]
set_property PACKAGE_PIN Y19      [get_ports clkcln_sle]

# Misc output to drive all DRS4 DENABLE pins
set_property IOSTANDARD  LVCMOS25 [get_ports drs_denable]
set_property PACKAGE_PIN W16      [get_ports drs_denable]

# To configure "clkdiv" lmk03000
set_property IOSTANDARD  LVCMOS25 [get_ports clkdiv_sclk]
set_property PACKAGE_PIN R16      [get_ports clkdiv_sclk]
set_property IOSTANDARD  LVCMOS25 [get_ports clkdiv_sdat]
set_property PACKAGE_PIN T17      [get_ports clkdiv_sdat]
set_property IOSTANDARD  LVCMOS25 [get_ports clkdiv_sle]
set_property PACKAGE_PIN R17      [get_ports clkdiv_sle]

# Generic lines to/from Artix7 FPGA
set_property IOSTANDARD  LVCMOS25 [get_ports a7_softreset]
# set_property PACKAGE_PIN R14      [get_ports a7_softreset]
set_property IOSTANDARD  LVDS_25  [get_ports {uztoa7spare[0]}]
set_property PACKAGE_PIN C20      [get_ports {uztoa7spare[0]}]
set_property IOSTANDARD  LVDS_25  [get_ports {uztoa7spare[1]}]
set_property PACKAGE_PIN B20      [get_ports {uztoa7spare[1]}]
set_property IOSTANDARD  LVDS_25  [get_ports {uztoa7spare[2]}]
set_property PACKAGE_PIN B19      [get_ports {uztoa7spare[2]}]
set_property IOSTANDARD  LVDS_25  [get_ports {uztoa7spare[3]}]
set_property PACKAGE_PIN A20      [get_ports {uztoa7spare[3]}]
set_property IOSTANDARD  LVDS_25  [get_ports {uztoa7spare[4]}]
set_property PACKAGE_PIN E17      [get_ports {uztoa7spare[4]}]
set_property IOSTANDARD  LVDS_25  [get_ports {uztoa7spare[5]}]
set_property PACKAGE_PIN D18      [get_ports {uztoa7spare[5]}]
set_property IOSTANDARD  LVDS_25  [get_ports {uztoa7spare[6]}]
set_property PACKAGE_PIN D19      [get_ports {uztoa7spare[6]}]
set_property IOSTANDARD  LVDS_25  [get_ports {uztoa7spare[7]}]
set_property PACKAGE_PIN D20      [get_ports {uztoa7spare[7]}]
set_property IOSTANDARD  LVDS_25  [get_ports {uztoa7spare[8]}]
set_property PACKAGE_PIN E18      [get_ports {uztoa7spare[8]}]
set_property IOSTANDARD  LVDS_25  [get_ports {uztoa7spare[9]}]
set_property PACKAGE_PIN E19      [get_ports {uztoa7spare[9]}]
set_property IOSTANDARD  LVDS_25  [get_ports {uztoa7spare[10]}]
set_property PACKAGE_PIN F16      [get_ports {uztoa7spare[10]}]
set_property IOSTANDARD  LVDS_25  [get_ports {uztoa7spare[11]}]
set_property PACKAGE_PIN F17      [get_ports {uztoa7spare[11]}]
set_property IOSTANDARD  LVDS_25  [get_ports {uztoa7spare[12]}]
set_property PACKAGE_PIN L19      [get_ports {uztoa7spare[12]}]
set_property IOSTANDARD  LVDS_25  [get_ports {uztoa7spare[13]}]
set_property PACKAGE_PIN L20      [get_ports {uztoa7spare[13]}]
set_property IOSTANDARD  LVDS_25  [get_ports {uztoa7spare[14]}]
set_property PACKAGE_PIN M19      [get_ports {uztoa7spare[14]}]
set_property IOSTANDARD  LVDS_25  [get_ports {uztoa7spare[15]}]
set_property PACKAGE_PIN M20      [get_ports {uztoa7spare[15]}]
set_property IOSTANDARD  LVDS_25  [get_ports {a7touzspare[0]}]
set_property PACKAGE_PIN M17      [get_ports {a7touzspare[0]}]
set_property IOSTANDARD  LVDS_25  [get_ports {a7touzspare[1]}]
set_property PACKAGE_PIN M18      [get_ports {a7touzspare[1]}]
set_property IOSTANDARD  LVDS_25  [get_ports {a7touzspare[2]}]
set_property PACKAGE_PIN K19      [get_ports {a7touzspare[2]}]
set_property IOSTANDARD  LVDS_25  [get_ports {a7touzspare[3]}]
set_property PACKAGE_PIN J19      [get_ports {a7touzspare[3]}]
set_property IOSTANDARD  LVDS_25  [get_ports {a7touzspare[4]}]
set_property PACKAGE_PIN L16      [get_ports {a7touzspare[4]}]
set_property IOSTANDARD  LVDS_25  [get_ports {a7touzspare[5]}]
set_property PACKAGE_PIN L17      [get_ports {a7touzspare[5]}]
set_property IOSTANDARD  LVDS_25  [get_ports {a7touzspare[6]}]
set_property PACKAGE_PIN K17      [get_ports {a7touzspare[6]}]
set_property IOSTANDARD  LVDS_25  [get_ports {a7touzspare[7]}]
set_property PACKAGE_PIN K18      [get_ports {a7touzspare[7]}]
set_property IOSTANDARD  LVDS_25  [get_ports {a7touzspare[8]}]
set_property PACKAGE_PIN G17      [get_ports {a7touzspare[8]}]
set_property IOSTANDARD  LVDS_25  [get_ports {a7touzspare[9]}]
set_property PACKAGE_PIN G18      [get_ports {a7touzspare[9]}]
set_property IOSTANDARD  LVDS_25  [get_ports {a7touzspare[10]}]
set_property PACKAGE_PIN F19      [get_ports {a7touzspare[10]}]
set_property IOSTANDARD  LVDS_25  [get_ports {a7touzspare[11]}]
set_property PACKAGE_PIN F20      [get_ports {a7touzspare[11]}]
set_property IOSTANDARD  LVDS_25  [get_ports {a7touzspare[12]}]
set_property PACKAGE_PIN G19      [get_ports {a7touzspare[12]}]
set_property IOSTANDARD  LVDS_25  [get_ports {a7touzspare[13]}]
set_property PACKAGE_PIN G20      [get_ports {a7touzspare[13]}]
set_property IOSTANDARD  LVDS_25  [get_ports {a7touzspare[14]}]
set_property PACKAGE_PIN J20      [get_ports {a7touzspare[14]}]
set_property IOSTANDARD  LVDS_25  [get_ports {a7touzspare[15]}]
set_property PACKAGE_PIN H20      [get_ports {a7touzspare[15]}]

# To 74hc95 shift registers that drive infrequently-upated outputs
set_property IOSTANDARD  LVCMOS25 [get_ports sr_oe_n]
set_property PACKAGE_PIN V17      [get_ports sr_oe_n]
set_property IOSTANDARD  LVCMOS25 [get_ports sr_ds]
set_property PACKAGE_PIN W18      [get_ports sr_ds]
set_property IOSTANDARD  LVCMOS25 [get_ports sr_stcp]
set_property PACKAGE_PIN V18      [get_ports sr_stcp]
set_property IOSTANDARD  LVCMOS25 [get_ports sr_stcp0]
set_property PACKAGE_PIN W19      [get_ports sr_stcp0]
set_property IOSTANDARD  LVCMOS25 [get_ports sr_shcp]
set_property PACKAGE_PIN N17      [get_ports sr_shcp]
set_property IOSTANDARD  LVCMOS25 [get_ports sr_q55s]
set_property PACKAGE_PIN P15      [get_ports sr_q55s]

# To "idrom" ds2411, for unique serial number
set_property IOSTANDARD  LVCMOS25 [get_ports idrom_d]
# set_property PACKAGE_PIN P14      [get_ports idrom_d]

# High-speed waveform readout from Artix7
set_property IOSTANDARD  LVDS_25 [get_ports {ro_sdatp[0]}]
set_property PACKAGE_PIN Y16     [get_ports {ro_sdatp[0]}]
set_property DIFF_TERM   TRUE    [get_ports {ro_sdatp[0]}]
set_property IOSTANDARD  LVDS_25 [get_ports {ro_sdatn[0]}]
set_property PACKAGE_PIN Y17     [get_ports {ro_sdatn[0]}]
set_property DIFF_TERM   TRUE    [get_ports {ro_sdatn[0]}]
set_property IOSTANDARD  LVDS_25 [get_ports {ro_sdatp[1]}]
set_property PACKAGE_PIN W14     [get_ports {ro_sdatp[1]}]
set_property DIFF_TERM   TRUE    [get_ports {ro_sdatp[1]}]
set_property IOSTANDARD  LVDS_25 [get_ports {ro_sdatn[1]}]
set_property PACKAGE_PIN Y14     [get_ports {ro_sdatn[1]}]
set_property DIFF_TERM   TRUE    [get_ports {ro_sdatn[1]}]
set_property IOSTANDARD  LVDS_25 [get_ports {ro_sdatp[2]}]
set_property PACKAGE_PIN T16     [get_ports {ro_sdatp[2]}]
set_property DIFF_TERM   TRUE    [get_ports {ro_sdatp[2]}]
set_property IOSTANDARD  LVDS_25 [get_ports {ro_sdatn[2]}]
set_property PACKAGE_PIN U17     [get_ports {ro_sdatn[2]}]
set_property DIFF_TERM   TRUE    [get_ports {ro_sdatn[2]}]
set_property IOSTANDARD  LVDS_25 [get_ports {ro_sdatp[3]}]
set_property PACKAGE_PIN V15     [get_ports {ro_sdatp[3]}]
set_property DIFF_TERM   TRUE    [get_ports {ro_sdatp[3]}]
set_property IOSTANDARD  LVDS_25 [get_ports {ro_sdatn[3]}]
set_property PACKAGE_PIN W15     [get_ports {ro_sdatn[3]}]
set_property DIFF_TERM   TRUE    [get_ports {ro_sdatn[3]}]
set_property IOSTANDARD  LVDS_25 [get_ports ro_holdp]
set_property PACKAGE_PIN T14     [get_ports ro_holdp]
set_property IOSTANDARD  LVDS_25 [get_ports ro_holdn]
set_property PACKAGE_PIN T15     [get_ports ro_holdn]

# Register-file I/O to/from Artix7, for slow control
set_property IOSTANDARD  LVDS_25 [get_ports bus_wdatp]
# set_property PACKAGE_PIN U13     [get_ports bus_wdatp]
set_property IOSTANDARD  LVDS_25 [get_ports bus_wdatn]
# set_property PACKAGE_PIN V13     [get_ports bus_wdatn]
set_property IOSTANDARD  LVDS_25 [get_ports bus_rdatp]
# set_property PACKAGE_PIN V12     [get_ports bus_rdatp]
set_property DIFF_TERM   TRUE    [get_ports bus_rdatp]
set_property IOSTANDARD  LVDS_25 [get_ports bus_rdatn]
# set_property PACKAGE_PIN W13     [get_ports bus_rdatn]
set_property DIFF_TERM   TRUE    [get_ports bus_rdatn]

# Serial DACs to set various offset and common-mode voltages
set_property IOSTANDARD  LVCMOS25 [get_ports sdac_din]
set_property PACKAGE_PIN T20      [get_ports sdac_din]
set_property IOSTANDARD  LVCMOS25 [get_ports sdac_sclk]
set_property PACKAGE_PIN V20      [get_ports sdac_sclk]
set_property IOSTANDARD  LVCMOS25 [get_ports {sdac_syncn[0]}]
set_property PACKAGE_PIN U20      [get_ports {sdac_syncn[0]}]
set_property IOSTANDARD  LVCMOS25 [get_ports {sdac_syncn[1]}]
set_property PACKAGE_PIN W20      [get_ports {sdac_syncn[1]}]

# Added 2017-01-20
set_property IOSTANDARD  LVCMOS25 [get_ports iv_scl0]
set_property PACKAGE_PIN P16      [get_ports iv_scl0]
set_property IOSTANDARD  LVCMOS25 [get_ports iv_scl1]
# set_property PACKAGE_PIN U18      [get_ports iv_scl1]
set_property IOSTANDARD  LVCMOS25 [get_ports iv_sda0]
set_property PACKAGE_PIN P18      [get_ports iv_sda0]
set_property PULLTYPE    PULLUP   [get_ports iv_sda0]
set_property IOSTANDARD  LVCMOS25 [get_ports iv_sda1]
# set_property PACKAGE_PIN U19      [get_ports iv_sda1]
set_property PULLTYPE    PULLUP   [get_ports iv_sda1]
set_property IOSTANDARD  LVCMOS25 [get_ports pgood6]
set_property PACKAGE_PIN R18      [get_ports pgood6]
set_property IOSTANDARD  LVCMOS25 [get_ports clkcln_lckdtct]
# set_property PACKAGE_PIN U15      [get_ports clkcln_lckdtct]
set_property IOSTANDARD  LVCMOS25 [get_ports clkdiv_lckdtct]
# set_property PACKAGE_PIN U14      [get_ports clkdiv_lckdtct]
set_property IOSTANDARD  LVCMOS25 [get_ports misc_tp]
set_property PACKAGE_PIN J18      [get_ports misc_tp]
set_property IOSTANDARD  LVCMOS25 [get_ports tpspare_1]
set_property PACKAGE_PIN H16      [get_ports tpspare_1]
set_property IOSTANDARD  LVCMOS25 [get_ports tpspare_2]
set_property PACKAGE_PIN H17      [get_ports tpspare_2]
set_property IOSTANDARD  LVCMOS25 [get_ports tpspare_3]
set_property PACKAGE_PIN N15      [get_ports tpspare_3]
set_property IOSTANDARD  LVCMOS25 [get_ports tpspare_4]
set_property PACKAGE_PIN N16      [get_ports tpspare_4]
set_property IOSTANDARD  LVCMOS25 [get_ports tpspare_5]
set_property PACKAGE_PIN M14      [get_ports tpspare_5]
set_property IOSTANDARD  LVCMOS25 [get_ports tpspare_6]
set_property PACKAGE_PIN M15      [get_ports tpspare_6]

# A few LEDs wired directly to MicroZed (Bank 13)
set_property IOSTANDARD LVCMOS25 [get_ports {uzled[0]}]
set_property PACKAGE_PIN V8 [get_ports {uzled[0]}]

set_property IOSTANDARD LVCMOS25 [get_ports {uzled[1]}]
set_property PACKAGE_PIN T5 [get_ports {uzled[1]}]

set_property IOSTANDARD LVCMOS25 [get_ports {uzled[2]}]
set_property PACKAGE_PIN W8 [get_ports {uzled[2]}]

set_property IOSTANDARD LVCMOS25 [get_ports {uzled[3]}]
set_property PACKAGE_PIN U5 [get_ports {uzled[3]}]

# wja 2018-05-18
# LEDs from Microzed IO Carrier Card from Adrian
set_property IOSTANDARD LVCMOS25 [get_ports {iocc_led[0]}]
set_property PACKAGE_PIN U14 [get_ports {iocc_led[0]}]

set_property IOSTANDARD LVCMOS25 [get_ports {iocc_led[1]}]
set_property PACKAGE_PIN U15 [get_ports {iocc_led[1]}]

set_property IOSTANDARD LVCMOS25 [get_ports {iocc_led[2]}]
set_property PACKAGE_PIN U18 [get_ports {iocc_led[2]}]

set_property IOSTANDARD LVCMOS25 [get_ports {iocc_led[3]}]
set_property PACKAGE_PIN U19 [get_ports {iocc_led[3]}]

set_property IOSTANDARD LVCMOS25 [get_ports {iocc_led[4]}]
set_property PACKAGE_PIN R19 [get_ports {iocc_led[4]}]

set_property IOSTANDARD LVCMOS25 [get_ports {iocc_led[5]}]
set_property PACKAGE_PIN V13 [get_ports {iocc_led[5]}]

set_property IOSTANDARD LVCMOS25 [get_ports {iocc_led[6]}]
set_property PACKAGE_PIN P14 [get_ports {iocc_led[6]}]

set_property IOSTANDARD LVCMOS25 [get_ports {iocc_led[7]}]
set_property PACKAGE_PIN R14 [get_ports {iocc_led[7]}]



set_property DONT_TOUCH true [get_cells bd_i/processing_system7_0/inst]
set_property DONT_TOUCH true [get_cells bd_i/processing_system7_0]
# set_property DONT_TOUCH true [get_cells bd_i/processing_system7_0_axi_periph/s00_couplers/auto_pc]
# set_property DONT_TOUCH true [get_cells bd_i/processing_system7_0_axi_periph]
# set_property DONT_TOUCH true [get_cells bd_i/rst_processing_system7_0_100M]
set_property DONT_TOUCH true [get_cells bd_i/wja_bus_lite_0]
set_property DONT_TOUCH true [get_cells bd_i]


create_clock -period 10.000 -name clk100_p -waveform {0.000 5.000} [get_ports clk100_p]
create_clock -period 10.000 -name mcuclk_copy_p -waveform {0.000 5.000} [get_ports mcuclk_copy_p]

# wja 2017-04-11
set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks clk100_p]
set_false_path -from [get_clocks clk100_p] -to [get_clocks clk_fpga_0]
set_false_path -from [get_clocks clk100_p] -to [get_clocks clk100_ps*]

